parser: babel-eslint
extends:
  - plugin:react/recommended
  - prettier
  - prettier/flowtype
plugins:
  - react
  - jest
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
env:
  es6: true
  browser: true
  jest/globals: true
rules:
  valid-typeof:
    - error
    -
      requireStringLiterals: false